<?php
/**
 * Do not edit this file. Edit the config files found in the config/ dir instead.
 * Test-specific configuration is found in config/environments/testing.php.
 */
require_once dirname( __DIR__ ) . '/vendor/autoload.php';
if ( isset( $_SERVER['WP_ENV'] ) && ! isset( $_ENV['WP_ENV'] ) ) {
		// phpcs:ignore WordPress.Security.ValidatedSanitizedInput.MissingUnslash, WordPress.Security.ValidatedSanitizedInput.InputNotSanitized
		$_ENV['WP_ENV'] = $_SERVER['WP_ENV'];
}
require_once dirname( __DIR__ ) . '/bedrock/config/application.php';
